#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Feb 15 20:59:20 EST 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto fb2f9ba6e24f4888a4627acbe38d9af9 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_sigmoid_sign_behav xil_defaultlib.tb_sigmoid_sign xil_defaultlib.glbl -log elaborate.log"
xelab -wto fb2f9ba6e24f4888a4627acbe38d9af9 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_sigmoid_sign_behav xil_defaultlib.tb_sigmoid_sign xil_defaultlib.glbl -log elaborate.log

